# Generated by Django 6.0.4 on 2026-04-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('organiser_name', models.CharField(max_length=100)),
                ('scheduled_for', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('agenda', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='organisation.team')),
            ],
            options={
                'ordering': ['scheduled_for', 'id'],
            },
        ),
    ]
